workflows:
  ios-workflow:
    name: Build iOS App
    max_build_duration: 60
    integrations:
      app_store_connect: KB23KMBMM5
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS release
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
