workflows:
  ios-workflow:
    name: Build iOS App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_STORE_CONNECT_ISSUER_ID: Environnement
        APP_STORE_CONNECT_KEY_IDENTIFIER: Environnement
        APP_STORE_CONNECT_PRIVATE_KEY: Environnement
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS release
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
